ota:
substitutions:
  device_id: "mmwave-zone-1"
  friendly_name: "Zone 1 Radar"
  esp32_board: "esp32-c3-devkitm-1"
  ld2450_tx_pin: "GPIO21"
  ld2450_rx_pin: "GPIO20"
  target_refresh_interval: "250ms"
  room_width_mm: "4200"
  room_depth_mm: "3600"
  sensor_origin_x_mm: "2100"
  sensor_origin_y_mm: "150"

packages:
  ld2450_multizone: !include packages/ld2450_multizone.yaml