# =============================================================================
# LD2450 Multi-zone Package
# Shared by all LD2450-based ESPHome nodes.
# =============================================================================

# --- Core firmware metadata -------------------------------------------------
esphome:
  name: ${device_id}

# --- External components ----------------------------------------------------
external_components:
  - source: custom_components
    components:
      - ld2450

# --- ESP32 target -----------------------------------------------------------
esp32:
  variant: ESP32C3
  board: ${esp32_board}
  framework:
    type: esp-idf

# --- Diagnostics ------------------------------------------------------------
logger:
  baud_rate: 0
  hardware_uart: USB_SERIAL_JTAG

# --- Connectivity -----------------------------------------------------------
api:

ota:
  platform: esphome

# --- Wi-Fi settings ---------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# --- UART bus (LD2450) ------------------------------------------------------
uart:
  id: uart_bus
  tx_pin: ${ld2450_tx_pin}
  rx_pin: ${ld2450_rx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# --- LD2450 component -------------------------------------------------------
ld2450:
  id: ld2450_radar
  uart_id: uart_bus

# --- Utility scripts --------------------------------------------------------
script:
  - id: configure_ld2450_uart
    mode: queued
    then:
      - logger.log: "LD2450: entering configuration mode"
      - lambda: |-
          static const uint8_t enable_cfg[] = {0xFD, 0xFC, 0xFB, 0xFA, 0x04, 0x00, 0xFF, 0x00, 0x01, 0x00, 0x04, 0x03, 0x02, 0x01};
          id(uart_bus).write_array(enable_cfg, sizeof(enable_cfg));
      - delay: 100ms
      - logger.log: "LD2450: disabling Bluetooth radio"
      - lambda: |-
          static const uint8_t disable_bt[] = {0xFD, 0xFC, 0xFB, 0xFA, 0x04, 0x00, 0xA4, 0x00, 0x00, 0x00, 0x04, 0x03, 0x02, 0x01};
          id(uart_bus).write_array(disable_bt, sizeof(disable_bt));
      - delay: 100ms
      - logger.log: "LD2450: setting UART baud to 256000"
      - lambda: |-
          static const uint8_t set_baud_256k[] = {0xFD, 0xFC, 0xFB, 0xFA, 0x04, 0x00, 0xA1, 0x00, 0x07, 0x00, 0x04, 0x03, 0x02, 0x01};
          id(uart_bus).write_array(set_baud_256k, sizeof(set_baud_256k));
      - delay: 100ms
      - logger.log: "LD2450: restarting module"
      - lambda: |-
          static const uint8_t restart_md[] = {0xFD, 0xFC, 0xFB, 0xFA, 0x02, 0x00, 0xA3, 0x00, 0x04, 0x03, 0x02, 0x01};
          id(uart_bus).write_array(restart_md, sizeof(restart_md));

# --- Sensors ----------------------------------------------------------------
sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: "${friendly_name} Active Targets"
      icon: mdi:counter
    target_1:
      x:
        name: "${friendly_name} Target 1 X"
        id: target_1_x
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-x-arrow
      y:
        name: "${friendly_name} Target 1 Y"
        id: target_1_y
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-y-arrow
      speed:
        name: "${friendly_name} Target 1 Speed"
        id: target_1_speed
        unit_of_measurement: "m/s"
        icon: mdi:speedometer
      resolution:
        name: "${friendly_name} Target 1 Resolution"
        id: target_1_resolution
        icon: mdi:target-variant
    target_2:
      x:
        name: "${friendly_name} Target 2 X"
        id: target_2_x
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-x-arrow
      y:
        name: "${friendly_name} Target 2 Y"
        id: target_2_y
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-y-arrow
      speed:
        name: "${friendly_name} Target 2 Speed"
        id: target_2_speed
        unit_of_measurement: "m/s"
        icon: mdi:speedometer
      resolution:
        name: "${friendly_name} Target 2 Resolution"
        id: target_2_resolution
        icon: mdi:target-variant
    target_3:
      x:
        name: "${friendly_name} Target 3 X"
        id: target_3_x
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-x-arrow
      y:
        name: "${friendly_name} Target 3 Y"
        id: target_3_y
        unit_of_measurement: "mm"
        accuracy_decimals: 0
        icon: mdi:axis-y-arrow
      speed:
        name: "${friendly_name} Target 3 Speed"
        id: target_3_speed
        unit_of_measurement: "m/s"
        icon: mdi:speedometer
      resolution:
        name: "${friendly_name} Target 3 Resolution"
        id: target_3_resolution
        icon: mdi:target-variant

  - platform: template
    name: "${friendly_name} Target 1 Distance"
    id: target_1_distance
    unit_of_measurement: "m"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
    update_interval: ${target_refresh_interval}
    lambda: |-
      if (isnan(id(target_1_x).state) || isnan(id(target_1_y).state)) {
        return NAN;
      }
      return hypotf(id(target_1_x).state, id(target_1_y).state) / 1000.0f;

  - platform: template
    name: "${friendly_name} Target 2 Distance"
    id: target_2_distance
    unit_of_measurement: "m"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
    update_interval: ${target_refresh_interval}
    lambda: |-
      if (isnan(id(target_2_x).state) || isnan(id(target_2_y).state)) {
        return NAN;
      }
      return hypotf(id(target_2_x).state, id(target_2_y).state) / 1000.0f;

  - platform: template
    name: "${friendly_name} Target 3 Distance"
    id: target_3_distance
    unit_of_measurement: "m"
    accuracy_decimals: 2
    icon: mdi:map-marker-distance
    update_interval: ${target_refresh_interval}
    lambda: |-
      if (isnan(id(target_3_x).state) || isnan(id(target_3_y).state)) {
        return NAN;
      }
      return hypotf(id(target_3_x).state, id(target_3_y).state) / 1000.0f;

# --- Text sensors -----------------------------------------------------------
text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "${friendly_name} LD2450 Firmware"
    mac_address:
      name: "${friendly_name} LD2450 MAC"
  - platform: template
    name: "${friendly_name} Target Snapshot"
    id: target_snapshot
    icon: mdi:radar
    update_interval: ${target_refresh_interval}
    lambda: |-
      return esphome::json::build_json([&](JsonObject root) {
        root["timestamp_ms"] = millis();
        root["room_width_mm"] = ${room_width_mm};
        root["room_depth_mm"] = ${room_depth_mm};
        root["sensor_origin_x_mm"] = ${sensor_origin_x_mm};
        root["sensor_origin_y_mm"] = ${sensor_origin_y_mm};
        JsonArray targets = root["targets"].to<JsonArray>();
        auto add_target = [&](int index, float x, float y, float speed, float resolution) {
          JsonObject obj = targets.add<JsonObject>();
          const bool valid = !(isnan(x) || isnan(y));
          obj["index"] = index;
          obj["valid"] = valid;
          obj["x_mm"] = valid ? x : 0.0f;
          obj["y_mm"] = valid ? y : 0.0f;
          obj["speed_mps"] = (!isnan(speed) && valid) ? speed : 0.0f;
          obj["resolution"] = (!isnan(resolution) && valid) ? resolution : 0.0f;
          obj["distance_mm"] = valid ? hypotf(x, y) : 0.0f;
        };
        add_target(1, id(target_1_x).state, id(target_1_y).state, id(target_1_speed).state, id(target_1_resolution).state);
        add_target(2, id(target_2_x).state, id(target_2_y).state, id(target_2_speed).state, id(target_2_resolution).state);
        add_target(3, id(target_3_x).state, id(target_3_y).state, id(target_3_speed).state, id(target_3_resolution).state);
      });

# --- Web server -------------------------------------------------------------
web_server:
  port: 80

# --- Binary sensors ---------------------------------------------------------
binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "${friendly_name} Occupancy"
      device_class: occupancy
      icon: mdi:motion-sensor

# --- Maintenance buttons ----------------------------------------------------
button:
  - platform: template
    name: "${friendly_name} Configure LD2450 UART"
    icon: mdi:chip
    on_press:
      - script.execute: configure_ld2450_uart
